---
title: "Erebus Random Forest"
author: "Mafalda S. Baptista"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE, 
                      warning = FALSE,
                      fig.align = "center",
                      fig.width = 10,
                      fig.height = 6)
```


```{r}
# Libraries

library("tidyverse")       # data wrangling and visualisation
library("phyloseq")        # analysis of microbial communities
library("randomForest")    # random forest analysis
library("caret")           # model training 
library("patchwork")       # plots together
library("here")            # set the path to the folder
library("pROC")            # analyze ROC curves
library("reshape")
library("RColorBrewer") #color package
library("scales")
library("psych")
library("microbiome") #for analyzing phyloseq objects
library("svglite") #for saving SVGs

set.seed(57)
```


```{r}

# This phyloseq object has the ASVs numbered and the correct metadata 

erebus <- readRDS("erebus")  # 1018
erebus

```


```{r}

# Filter the data

erebusf <- subset_taxa (erebus, (Kingdom !="Eukaryota")) 
erebusf <- subset_taxa (erebusf, (Order !="Chloroplast") | is.na(Order)) 
erebusf <- subset_taxa (erebusf, (Family != "Mitochondria") | is.na(Family)) 
erebusf
```

```{r}
# Trim low abundance ASVs
seq_flt <- genefilter_sample(erebusf, filterfun_sample(function(x) x > 10), A = 2) 
# Why 10? Because it gives ~350 ASVs which is what we had after filtering rel abund > 0.1 %

erebusf1 <- prune_taxa(seq_flt, erebusf)
erebusf1

# Transform data using centered log ratio (clr)
erebus_clr <- microbiome::transform(erebusf1, "clr")
```
We keep Phyla NA (which are numerous - check Erebus_Data_Analysis.Rmd for this info)
We also keep all ASVs and don't filter for > than 2 (they are only 65) - also explained in Erebus_Data_Analysis.Rmd


```{r}
# Select ASVs (or other taxonomic level if appropriate)
predictors <- otu_table(erebus_clr)

# Select the response variable - in this case Site
response.site <- as.factor(sample_data(erebus_clr)$Site)

# Combine into 1 data frame
rf.data.site <- data.frame(response.site, predictors)

# Split the data in training and test
N <- nrow(rf.data.site) # how many rows we have

train_id <- sample(x = 1:N,
                   size = round(N * 0.66, 1),
                   replace = T)

train <- rf.data.site[train_id, ]
test <- rf.data.site[-train_id, ]

# Run the random forest
rf.site <- randomForest(response.site~., data = rf.data.site, ntree = 1000) 
rf.site

varImpPlot(rf.site)


# Predict response
test$Predicted_Class <- predict(rf.site,
                                newdata = test,
                                type = "response")


# Get the predicted class probabilities
pred_prob <- predict(
  rf.site,
  newdata = test,
  type = "prob")

# Add the probabilities to the test set
test <- cbind(test, pred_prob)
test %>% head()

# Look at some of the errors
test_errors <- test %>%
  filter(response.site != Predicted_Class)

test_errors %>%
  head()

# Confusion matrix
confusionMatrix(test$Predicted_Class, test$response.site)

# Calculate ROC Curve
roc <- multiclass.roc(response = test$response.site,
               predictor = as.numeric(predict(rf.site,
                                   newdata = test,
                                   type = "response")))


# Plot ROC
rs <- roc[["rocs"]]
plot.roc(rs[[1]])


# Get AUC
auc <- auc(roc)
auc
```


```{r}
# Select the response variable - in this case Transect
response.trans <- as.factor(sample_data(erebus_clr)$Transect)

# Combine into 1 data frame
rf.data.trans <- data.frame(response.trans, predictors)

# Split the data in training and test
train <- rf.data.trans[train_id, ]   # if you keep the same train/ test as before you compare better the outcome site vs transect
test <- rf.data.trans[-train_id, ]

# Run the random forest
rf.trans <- randomForest(response.trans~., data = rf.data.trans, ntree = 1000) 
rf.trans

varImpPlot(rf.trans)


# Predict response
test$Predicted_Class <- predict(rf.trans,
                                newdata = test,
                                type = "response")


# Get the predicted class probabilities
pred_prob <- predict(
  rf.trans,
  newdata = test,
  type = "prob")

# Add the probabilities to the test set
test <- cbind(test, pred_prob)
test %>% head()

# Look at some of the errors
test_errors <- test %>%
  filter(response.trans != Predicted_Class)

test_errors %>%
  head()

# Confusion matrix
confusionMatrix(test$Predicted_Class, test$response.trans)

# Calculate ROC Curve
roc <- multiclass.roc(response = test$response.trans,
               predictor = as.numeric(predict(rf.trans,
                                   newdata = test,
                                   type = "response")))


# Plot ROC
rs <- roc[["rocs"]]
plot.roc(rs[[1]])


# Get AUC
auc <- auc(roc)
auc
```


```{r}
# what ASVs are important?
imp.trans<- data.frame(importance(rf.trans))
imp.trans<- imp.trans %>%
  rownames_to_column() %>%
  dplyr::rename(ASV = rowname)

#remove ASVs with 0 Gini value and reorder the data
imp.trans_mod <- imp.trans[which(imp.trans$MeanDecreaseGini>0),]
imp.trans_ord <- imp.trans_mod[order(imp.trans_mod$MeanDecreaseGini, decreasing = TRUE),]

#for looking at the Gini values to see where the "elbow" is
imp.trans_ord$ASV <- reorder(imp.trans_ord$ASV, -imp.trans_ord$MeanDecreaseGini)

ggplot(data = imp.trans_ord, aes(x= ASV, y = MeanDecreaseGini)) +
  geom_col(width = 1) +
  geom_hline(yintercept = 0.06, color = "orange", linetype = "dashed") +
  ylab("Mean Decrease in Gini value") +
  theme_bw() + 
  theme(
    axis.text.x  = element_blank(),
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank())
  
#looks like the elbow is around Gini values of 0.06; reduces number of ASVs to ~30
imp.trans_final <- imp.trans_ord[which(imp.trans_ord$MeanDecreaseGini>0.06),]
nrow(imp.trans_final)

#try reducing the # of taxa even more
imp.trans_small <- imp.trans[which(imp.trans$MeanDecreaseGini>0.09),]
nrow(imp.trans_small)


```

```{r}
####get taxonomy and abundance info added onto new data
#get taxa info
site.asvs<- imp.trans_final$ASV
site.taxa <- data.frame(tax_table(erebus_clr)) %>% 
  rownames_to_column() %>%
  dplyr::rename(ASV = rowname) %>%
  filter(ASV %in% site.asvs)

rf.site.data <- left_join(site.taxa, imp.trans_final, by = "ASV")

#extract abundance information
site.ab <- data.frame(otu_table(erebus_clr)) 

site.ab <- as.data.frame(t(site.ab)) %>%
  rownames_to_column() %>%
  dplyr::rename(ASV = rowname) %>%
  filter(ASV %in% site.asvs)

#combine taxa info with abundance info
rf.site.data_all <- left_join(rf.site.data, site.ab, by = "ASV")

```

```{r}
#Heatmap of ASVs that allow for discriminating between transects
#replace NA in Phylum with Unassigned
rf.site.data_all$Phylum[is.na(rf.site.data_all$Phylum)] <- 'Unassigned'

rf.site.data_all["Phylum"][rf.site.data_all["Phylum"] == "Crenarchaeota"] <- "Thaumarchaeota"

rf.site.data_all$ASV_Phylum = paste(rf.site.data_all$Kingdom,
                                    rf.site.data_all$Phylum, rf.site.data_all$ASV) 

rf.site.data_all$MeanDecreaseGini <- factor(rf.site.data_all$MeanDecreaseGini)

rf.site.melt <- melt(rf.site.data_all)
rf.site.melt$variable <- as.character(rf.site.melt$variable)

#Add Transect and Site info
rf.site.melt <- rf.site.melt %>%
  mutate(Site = case_when(
    startsWith(variable, "T") ~ "Tramway Ridge",
    startsWith(variable, "W") ~ "Western Crater"
  ))

rf.site.melt <- rf.site.melt %>%
  mutate(Transect = case_when(
    startsWith(variable, "TR1") ~ "TR1",
    startsWith(variable, "TR2") ~ "TR2",
    startsWith(variable, "WC") ~ "WC"
  ))

rf.site.melt$MeanDecreaseGini <- as.numeric(rf.site.melt$MeanDecreaseGini)

#plot
heatmap_f <- ggplot(rf.site.melt, aes(variable, ASV_Phylum)) +
  geom_tile(aes(fill = value)) +
  theme_bw() +
  scale_fill_distiller('CLR \nAbundance', palette = "YlOrRd", direction = 1) +
  ylab("Kingdom, Phylum, ASV #") +
  xlab("Temperature (\u00b0C)") +
  theme(
    axis.title.x = element_text (size=16),
    axis.text.x  = element_text(size=14, angle = 45,
                                hjust= 1.3, vjust=1.3),
    axis.title.y = element_text(size=16),
    axis.text.y  = element_text(size=10),
    strip.text.x = element_text(size = 14),
    legend.text = element_text(size=14),
    legend.title = element_text(size=14)) +
  facet_grid(.~Transect, scales = "free")

heatmap_f

#ggsave("RFheatmap.png", heatmap_f, width = 240, height = 240, units = "mm",dpi = 300)

#ggsave("RFheatmap.svg", heatmap_f, width = 240, height = 240, units = "mm",dpi = 300)

```

```{r}
#print taxa table
rf.site.data_all <- rf.site.data_all[order(rf.site.data_all$ASV_Phylum,
                                           decreasing = FALSE),]
#write.csv(rf.site.data_all[c(24,1,9,2:8)], "Table S4.csv")
```


```{r}
#Prepare data into matrix for alternate heatmap function
rf.site.ab <- dplyr::select(rf.site.data_all, -c(ASV, Kingdom,
                                                 Phylum, Class,
                                                 Order, Family,
                                                 Genus, Species,
                                                 MeanDecreaseGini,
                                                 ASV_Phylum))

rownames(rf.site.ab) <- rf.site.data_all$ASV_Phylum

#Alternate heatmap using heatmap function; need matrix
rf.site.ab.mx <- as.matrix(rf.site.ab)

#heatmap
heatmap(rf.site.ab.mx, scale="column",
        xlab = "Sample", cexRow = 0.5,
        col = colorRampPalette(brewer.pal(8, "RdPu"))(25))
legend(x="left", legend=c("min", "avg", "max"),
       fill=colorRampPalette(brewer.pal(8, "RdPu"))(3))

```
